### ISSUE TITLE
Nekompatibilita s 1.6.1.11

### ISSUE THREAD

**Issue by zol1k** [Zasilkovna/prestashop#10]
Api kluc nam nechce z nejakeho dovodu vziat. Skusali sme starsiu verziu, tam slo bez problemov. My vsak potrebujeme sfunkcnit na 1.6.1.11. Najaktualnejsia verzia 1.6PS. Da sa to poriesit?

**Comment by jarkokiliman** [comment]
Mam rovnaky problem...
Najde sa niekto s riesenim? 
Starsie verzie PS mi z nejakeho dovodu nejdu nainstalovat (chyba pri 23% instalacie), a nove nepodporuju modul Zasilkovny. Neprijemna situacia.. :)

**Comment by matyx** [comment]
Dobrý den,
kontaktujte nás prosím na technicka.podpora@zasilkovna.cz, zkusíme se podívat kde je problém.
