### ISSUE TITLE
Přenos údajů z widgetu

### ISSUE THREAD

**Issue by msmitka** [Zasilkovna/prestashop#105]
Dva dny zpět se do objednávky začal přenášel údaj Please select pickup point, po dnešní aktualizaci modulu na verzi 2.1.6 je pole v db prázdné.
Verze PrestaShopu: 1.7.6.5
Verze PHP: 7.2.30
Verze MySQL: 5.7.32

![image](https://user-images.githubusercontent.com/46485311/121815622-b54f9c00-cc77-11eb-878a-75a14c23c3b5.png)

**Comment by packeta** [comment]
Pokud dojde k výpadku widgetu v6 (který náš modul využívá) je provoz automaticky přesměrován na původní verzi widgetu.  Chybou v našem modulu nedojde v takovém případě k uložení vybraného výdejního místa do databáze.  Co nejdříve vydáme novou verzi modulu, kde bude tento problém již vyřešen.

**Comment by packeta** [comment]
Tento problém byl opraven v nově vydané verzi 2.1.7
