### ISSUE TITLE
PrestaShop 1.7

### ISSUE THREAD

**Issue by jarkokiliman** [Zasilkovna/prestashop#11]
Pracuje sa na module pre najnovsiu verziu PS 1.7?
Diky

**Comment by matyx** [comment]
Dobrý den,
pracuje, počítáme s vydáním do měsíce.

**Comment by faminepq** [comment]
Zdravím, nějaké novinky? Máme připravený nový eshop, ale čekáme na tento modul...

**Comment by matyx** [comment]
Dobrý den, vydání nové verze předpokládáme koncem dubna.

**Comment by Tomkinss** [comment]
Ahoj @faminepq ak ti to ponahla, mozem ti docastne poslat modul, ktory som upravil, aby fungoval pre verziu 1.7+. Pouzivam ho u mna na eshope [benchpress.sk](https://www.benchpress.sk) Ked vyjde stable verzia mozes si ju aktualizovat.

**Comment by faminepq** [comment]
@Tomkinss to bys byl moc hodnej! Celkem to právě spěchá... PS: @matyx - nepomohla by tato úprava i při vydání nové oficiální verze? (žádný commit pro PS 1.7 tu ještě není)

**Comment by matyx** [comment]
@Tomkinss Pokud máte úpravu pro verzi 1.7, nechcete ji začlenit do našeho pluginu (třeba poslat PR :) )? 
@faminepq chystáme nový plugin, který toho bude umět více než současný (např. automatické podávání zásilek přímo z administrace eshopu), proto nám přizpůsobení pro novou verzi trvá déle než obvykle - prosíme o trpělivost.

**Comment by Tomkinss** [comment]
@matyx ta uprava nieje uplne final. Napriklad stranka s exportom .csv je bez designu. Nechcelo sa mi riesit design, nakolko hned po vydani verzie od Vas planujem prejst na nu. Podla toho co pises to bude super. Ako planujete riesit customizaciu widgetu na vyber odberneho miesta? Pevne verim ze sa to uz nebude tahat z .js

@faminepq tu to mas, hadam pomoze :)
[packetery.zip](https://github.com/Zasilkovna/prestashop/files/932311/packetery.zip)

**Comment by matyx** [comment]
@Tomkinss Máme v plánu výběr poboček renderovat z PHP, abychom tím omezili případné problémy s různými ajax košíky, ale podrobnosti k tomu momentálně nemám.

**Comment by faminepq** [comment]
Nějaké novinky?

**Comment by matyx** [comment]
Bohužel se nám realizace protáhla :disappointed: Ještě modul ladíme, aby byl co nejvíce uživatelsky přívětivý. Jakmile budeme mít alespoň testovací verzi, dáme do tohoto issue vědět.

**Comment by Ractor** [comment]
@matyx A máte alespoň nějakej odhad? Alespoň z hlediska té testovací verze (design je skutečně až na posledním místě). :)

@Tomkinss Je ta tvoje verze případně někde dostupná?

**Comment by matyx** [comment]
Zdravím všechny zúčastněné. V příloze je beta verze modulu k otestování. Budeme rádi, když ji vyzkoušíte a dáte nám feedback před tím, než modul pustíme do světa v ostré verzi. Na modulu ještě doděláváme překlady (ty v beta verzi nejsou), případné další připomínky nám prosím pište sem.

Děkujeme!

[packetery.v.1.8.9b.zip](https://github.com/Zasilkovna/prestashop/files/1062157/packetery.v.1.8.9b.zip)

**Comment by Ractor** [comment]
@matyx Zatím jsem narazil na to, že v konfiguraci na záložce settings chybí tlačítko na uložení + když chci založit nového dopravce, nevidím žádnou zemi.

**Comment by Ractor** [comment]
@matyx Tak problém je v poli na API key. Když ho zadám, napíše mi to, že má být hodnota String (což je), ale neuloží ji to.

**Comment by rivfaader** [comment]
@Ractor díky za info, o problému víme a v další verzi by měl být opraven, tenhle problém předpokládám brání v dalším testování?

**Comment by Ractor** [comment]
@rivfaader Jelikož nemůžu zadat zemi (nevím, zdali to s APIkey souvisí nebo ne, ale to je v podstatě fuk), tak nemůžu vytvořit dopravce, tudíž je to tak, nemůžu to dál testovat.

**Comment by rivfaader** [comment]
@Ractor vypadá to, že dostupné země se vytáhnou až ze seznamu poboček, který se v tomto případě ani nepodaří stáhnout. Jakmile bude nová verze, znovu ji sem nahrajeme.

**Comment by RomanRogy** [comment]
Dobrý den, prosím jak to vypadá s poslední verzí na 1.7, rád bych už zařadil Zásilkovnu do nového e-shopu.
Děkuji za odpověď, případně poslední verzi :-)

**Comment by rivfaader** [comment]
Dobrý den,

přikládám opravenou verzi modulu pro testování. Za jakékoliv připomínky budeme vděční.

[packetery.v.2.0.0rc2.zip](https://github.com/Zasilkovna/prestashop/files/1118517/packetery.v.2.0.0rc2.zip)

**Comment by rivfaader** [comment]
Fixed by dc93844
