### ISSUE TITLE
Přístup k objednávkám přes web service

### ISSUE THREAD

**Issue by vaclavvanik** [Zasilkovna/prestashop#12]
Dobrý den, pro napojení expedičního systému TouchStore bychom potřebovali, aby se přes web service dalo zjistit id výdejního místa.

**Comment by matyx** [comment]
Dobrý den,
to možné je, avšak nikoliv z prostředí Prestashopu. Informace můžete nalézt na stránkách https://www.zasilkovna.cz/pristup-k-pobockam/ (po přihlášení) nebo na https://docs.packetery.com (bez přihlášení). Případné další dotazy prosím směřujte na email technicka.podpora@zasilkovna.cz (jelikož se to netýká přímo modulu prestashop).

**Comment by PrestaShopExpert** [comment]
Existuje postup, jak přes PS WebServices načítat i další informace.
[http://webkul.com/blog/how-to-add-new-tables-in-rest-api-of-prestashop/](http://webkul.com/blog/how-to-add-new-tables-in-rest-api-of-prestashop/)

Petr Pánek
[www.prestashop.expert](www.prestashop.expert)

**Comment by vaclavvanik** [comment]
@matyx nerozumíte mi. Myslím načíst id pobočky u objednávek, které jsou v prestě.
@PrestaShopExpert díky za nápad na hotfix.
