### ISSUE TITLE
v 1.17 - odinstalace vs overrides

### ISSUE THREAD

**Issue by JaKaspar** [Zasilkovna/prestashop#13]
Dobrý den,
používám verzi 1.17 v Prestashopu 1.6.1.13
Odinstalace neodstraní override Carrier.php a pokus o instalaci v 1.18 končí chybou 

> "Nelze nainstalovat přepsání: Metoda __construct ve třídě Carrier je již přepsána."

Manuální odebrání souboru v Overrides, končí při následném pokusu o instalaci 1.18 chybou 

> Nelze nainstalovat přepsání: Class CarrierOverrideOriginal594b6870a7bd6 does not exist

Pokus o opětovnou instalaci 1.17, končí stejnou chybou, tzn. je na mrtvém bodě a nelze se pohnout ani vpřed, ani zpátky. Pomůže ruční odstranění override a smazání class_index.php v /Cache.
Toto by bylo třeba vyřešit v odinstalaci

**Comment by rivfaader** [comment]
Dobrý den,
problém byl vyřešen v novější verzi modulu.
