### ISSUE TITLE
Missing shipments in admin (Chybějící dopravci v admin)

### ISSUE THREAD

**Issue by janhonza** [Zasilkovna/prestashop#130]
Hello,
I have problem, that I have blank list of shippers, in module 2.1.3 it was OK.
Kind regards
Jan

![image](https://user-images.githubusercontent.com/89828645/131448273-064202bd-7979-46f4-bde3-fbbdd4fc6811.png)

Dobrý den, přeji,
v adminu nevidím dopravce, je platební možnosti. ve verzi 2.1.3 to fungovalo normálně.
Děkuji
Honza

**Comment by packeta** [comment]
Hello, please email us at technicka.podpora@zasilkovna.cz.
