### ISSUE TITLE
Type error: Argument 1 passed to Packeteryclass::loadWeightToOrders() must be of the type array

### ISSUE THREAD

**Issue by NikitaVrnv** [Zasilkovna/prestashop#138]
Hi everyone!

Last update brought the error on the page Orders->Zasilkovna Orders. Can you help me with that, please?
Type error: Argument 1 passed to Packeteryclass::loadWeightToOrders() must be of the type array, boolean given, called in /**********/modules/packetery/packetery.class.php on line 194
[Symfony\Component\Debug\Exception\FatalThrowableError 0]

Thank you in advance.

**Comment by jan-potuznik-z** [comment]
Hi Nikita, we're already working on a fix. Is it possible to provide screenshot of page "Advanced Parameters" > "Information"?
What is the situation, when this error occurs? (URL, action..) Thank you for clarification.

**Comment by NikitaVrnv** [comment]
> Hi Nikita, we're already working on a fix. Is it possible to provide screenshot of page "Advanced Parameters" > "Information"?
> What is the situation, when this error occurs? (URL, action..) Thank you for clarification.

Dear Jan,
The problem has been solved with the last update. Thank you for the support!
Regards

**Comment by jan-potuznik-z** [comment]
Can you please clarify what was updated, including the versions? We're still interested in fixing this problem. The screenshot will be also appreciated. Thank you, best regards, Jan.
