### ISSUE TITLE
Pomalost/nehospodárnost JavaScriptu

### ISSUE THREAD

**Issue by JaKaspar** [Zasilkovna/prestashop#14]
Dobrý den, nasazení modulu zdvojnásobilo dobu načítání stránky objednávky (jednokrokové), kde je nyní vidět průměrně dvou a půl vteřinové zpracování javascriptu. Hlavní příčinou je obrovský skript api.js. Bylo by vhodné defaultně načítat externí skripty asynchronně a zvážit jejich optimalizaci...
Děkuji

**Comment by matyx** [comment]
Dobrý den,
víme o tom, bohužel všechny informace o pobočkách se stahují najednou a proto je soubor tak velký. Řešením je vlastní implementace výdejních míst, případně můžete počkat na nový modul, který již JS API nepoužívá.
