### ISSUE TITLE
problém s instalací packeta, chybí seznam dopravců

### ISSUE THREAD

**Issue by jamiloo** [Zasilkovna/prestashop#142]
Dobrý den. Řeším problém při instalaci nové verze Packety do Prestashopu 1.7. Jedná se o multistore. Prestashop 1.7.2.2.
Nezobrazují se v rozhraní Packety dostupní dopravci, abych nakonfiguroval, co je a co není Zásilkovna. 
Původně byla nainstalována zásilkovna od ZLabs verze v2.0.3rc2. Tu jsem jako první krok odinstaloval. Nyní po instalaci se mi nedaří packetery dokonfigurovat z důvodü problému popsaného výše. Nemá někdo knowhow, co s tím? Děkuji.

**Comment by packeta** [comment]
Dobrý den, 
z bezpečnostních důvodů jsme odstranili váš screen.   Na screenu byl uvedeno vaše API heslo.  Kdokoli by mohl přes vás a na váš účet poslat zásilku.

K vašemu problému.  Náš modul v současné době multistore nepodporuje.   V tomto režimu modul nemusí správně pracovat.
Tlačítko pro přidání dopravy v nastavení modulu nenajdete.   Dopravní metodu musíte přidat v modulu Dopravci.  
V seznamu se zobrazují pouze aktivní dopravní metody.  
Napište nám prosím email na technicka.podpora@zasilkovna.cz a zkusíme problém vyřešit.
