### ISSUE TITLE
Nezapisuje se branch

### ISSUE THREAD

**Issue by jecminek** [Zasilkovna/prestashop#15]
Dobrý den, v modulu se úplně tak nevyznám, ale mám problém s tím, že se do databáze nazapisuje id_branch, name_branch a další data po úspěšném dokončení objednávky, nevím kde by se mohla chyba projevit?
Javascriptové pole se všemy místy, kde jsou zásilkovny se načítají v pořádku, pokud to otestuji s API key v odkazu.
Rád bych se vyhl přechodu na vyšší verzi prestashopu, kvůli ostatním modulům.

Verze prestashopu 1.6.1.2
Verze modulu v1.18 
Verze php 5.6.30

Děkuji vám za jakkoukoliv radu

**Comment by matyx** [comment]
Dobrý den,
napište nám prosím na technicka.podpora@zasilkovna.cz, ideálně pošlete i url eshopu, abychom se na problém mohli rovnou podívat. U ostatních klientů tento problém neevidujeme, chyba bude pravděpodobně způsobená kombinací modulů či nastavením.
