### ISSUE TITLE
Cron na automatický update výdejních míst

### ISSUE THREAD

**Issue by DegiCZ** [Zasilkovna/prestashop#155]
Dobrý den, nevíte jak udělat abych nemusel ručně aktualizovat výdejní místa ale aby to Cron udělal jednou denně za mě? Děkuji

**Comment by packeta** [comment]
Dobrý den, 

nevím jakou máte verzi našeho modulu, pokud ale nějakou novější verzi ve které je v košíku implementovaný náš widget pro výběr výdejních míst,  není třeba v nastavení modulu aktualizovat seznam výdejních míst každý den.  Stačí jen ve chvíli, kdy Zásilkovna přidá nového dopravce a vy jej budete chtít používat.  O aktualizaci výdejních míst se stará přímo widget.  V nejnovější verzi 2.1.12 v nastavení modulu aktualizace výdejních míst už není.   Nově je zde záložka "Dopravci" a ruční aktualizací se aktualizuje pouze seznam dopravců.  Ten není potřeba aktualizovat každý den, ale jen když budete chtít použít nového dopravce, který v seznamu ještě neuvidíte.
