### ISSUE TITLE
Stav objednávek v přehledu

### ISSUE THREAD

**Issue by webeshop** [Zasilkovna/prestashop#157]
Dobrý den, 

v seznamu objednávek (v modulu zásilkovny) není vidět stav objednávek. V modulu není ani žádný filtr, např. podle stavu objednávky, takže správce e-shopu neví, které objednávky může exportovat. (v seznamu jsou všechny objednávky) Je to problém hlavně u větších e-shopů. 

Je možné do budoucna toto vyřešit? 
Děkuji
Kotyra

**Comment by packeta** [comment]
Dobrý den,
náš modul toto zatím opravdu bohužel neumí.  Do budoucna s touto funkcí ale počítáme.
