### ISSUE TITLE
Aktualizace modulu z 2.1.10 na 2.1.13 - nefunkčnost administrace

### ISSUE THREAD

**Issue by PeNov** [Zasilkovna/prestashop#162]
Dobrý den,

po aktualizaci modulu z v2.1.10 na v2.1.13 je nefunkční administrace, chyba: HTTP ERROR 500.

Po aktivaci debug režimu přes sftp, administrace začne fungoval ale při pokusu konfigurovat modul dojde k chybě:

![image](https://user-images.githubusercontent.com/38213520/141281734-939a69da-3499-4c52-a01f-8c6748cada8a.png)

Děkuji
Přeji pěkný den

PS 1.7.7.8
PHP: 7.3.31-1

**Comment by jan-potuznik-z** [comment]
Dobrý den, 

otestoval jsem aktualizaci modulu z 2.1.10 na 2.1.13 v PrestaShopu 1.7.7.8 s PHP 7.3.29 a vše šlo v pořádku.

Můžete prosím podrobně popsat, jaký postup jste použil?

(Sloupec pickup_point_type byl přidán již ve verzi 2.1.5, bez něj by vám neměla fungovat ani verze 2.1.10.)

Děkuji.

**Comment by PeNov** [comment]
Postup byl následující:
Vždy zkouším nový modul v testovací instalaci, tedy modul není aktivně využíván.
Byl zapnut režim ladění.
Moduly, nahrát modul, vyberte soubor prestashop-1.7-modul-2.1.13
Po dokončení jsem kliknul hned na Konfigurace a tím následovala uvedená chyba.

Aktuálně jsem modul odinstaloval a smazal složku, nainstaloval 2.1.10, provedl aktualizaci na 2.1.13 což tentokrát proběhlo bez této chyby.
Jediné co zůstalo nefunkční byla administrace bez DEBUG režimu. Řešením je ručně vymazat var/cache/prod
Omlouvám se, nevím čím to bylo způsobené.
Udělám test na nějaké ostré instalaci.
Děkuji
Přeji pěkný den

**Comment by jan-potuznik-z** [comment]
Děkuji za doplnění. 

To vypadá, že cache Vaší testovací instalace byla neaktuální, nebo se nepovedla nějaká instalace/odinstalace. Dejte vědět, pokud byste se ještě setkal s nějakým problémem, jsme rádi za každou informaci, která pomůže zlepšit náš modul.

Hezký den.
