### ISSUE TITLE
Nelze načíst odběrová místa

### ISSUE THREAD

**Issue by Efkovole** [Zasilkovna/prestashop#169]
Pár dní nelze načíst odběrová místa. (Plugin nefunguje)  Načte pouze 93 odběrnýh míst. 

Nezměnila zásilkovna API?

Aktuálně se adresy podle mě čerpají z tohoto..? A když složím link s api, tak se mi načte opravdu pouze 93 položek... 
`  $branch_new_url = 'https://www.zasilkovna.cz/api/v4/' . $api_key . '/branch.xml?address-delivery';`

Něměla by řádka obsahovat něco jako... Ovšem pokud tak upravím, tak stejně nefunguje.. :/
`$branch_new_url = 'https://www.zasilkovna.cz/api/v4/' . $api_key . '/branch.xml';`

Prosím hééélp. :)

**Comment by Efkovole** [comment]
Problém odstraněn. Prostee pos.... PrestaShop...

**Comment by packeta** [comment]
Dobrý den, 

novější verze našeho modulu již v administraci nestahuje seznam výdejních míst, ale pouze seznam dopravců.  Již delší dobu bylo stahování seznamu výdejních míst v administraci zbytečné, protože modul obsahuje pro výběr výdejního místa (v košíku i v administraci) widget v6 který se aktualizuje zcela automaticky a tento seznam se nikde nepoužíval. Seznam dopravců se načítá pouze pro potřeby nastavení modulu (aby bylo možné přiřadit k přepravci PS dopravce Zásilkovny.
