### ISSUE TITLE
Export objednávky do Packety - SOAP-ERROR

### ISSUE THREAD

**Issue by radar6** [Zasilkovna/prestashop#198]
Vidím poprvné tuto chybu:

Order 58 Nevyexportováno! Chyba: SOAP-ERROR: Encoding: object has no 'weight' property
Order 58 Nevyexportováno! Chyba: No id given

Co to může být?

**Comment by radar6** [comment]
Chyba byla asi v tom, že tam byly v Prestashopu jiné hmotnostní jednotky (viz Mezinárodní -> Lokalizace), které se používají např. v Anglii, Americe. Proto se pak zobrazovala hláška  _**no 'weight' property**_ 
Bylo nastaveno na **_lbs_**, což modul neumí zpracovat (např. převést na kg)

**Comment by packeta** [comment]
Dobrý den,  pokud máte v PS nastavené nepodporované jednotky,  náš modul vás na to upozorní v nastavení modulu chybovou hláškou. Ve verzi 3.0 na které v současné době pracujeme, bude již podpora i dalších jednotek hmotnosti.
