### ISSUE TITLE
Nová verze pro PS 1.7

### ISSUE THREAD

**Issue by quentinocz** [Zasilkovna/prestashop#22]
Při zvolení pouze jedné země pro dopravu by měl dropdown box s výběrem země zmizet úplně nebo by měla být daná země automaticky defaultně zvolená.. Je v tomto případě zbytečná a přidává krok navíc.. Pokud je to možné, prosím o provedení tohoto vylepšení.
V upozornění je neustále "Klíč API Zásilkovny nebyl zadán." i když jej není kam zadat..
S pozdravem
DŠ

**Comment by matyx** [comment]
API klíč se zadává v nastavení modulu. Pokud se zobrazuje i přes to že je vyplněný, pošlete nám prosím screenshot kde se upozornění zobrazuje. Na možnost zlepšení UX vaším návrhem se podíváme, díky za něj.

**Comment by quentinocz** [comment]
@matyx 
V nastavení vidím pouze možnost zadat API heslo, API klíč nikoliv, ale zkušební objednávky byly úspěšně exportovány do podaných zásilek.. Přikládám screenshots.

<img width="1226" alt="snimek obrazovky 2017-08-10 v 21 30 52" src="https://user-images.githubusercontent.com/30895860/29188415-48310cc8-7e13-11e7-84e3-cb3ca1cce72c.png">
<img width="1440" alt="snimek obrazovky 2017-08-10 v 21 29 43" src="https://user-images.githubusercontent.com/30895860/29188416-4877ce4c-7e13-11e7-9c3c-ac2a4683fa22.png">

**Comment by krasnycz** [comment]
Muzete prosim doresit pozadavek z 10 srpna od quentinocz. Pokud je pouzita pouze jedna zeme mela by zmizet nutnost jejiho vyberu v listboxu. Drobna uprava, ktera ma zasadni vliv na pouzitelnost vaseho modulu.

**Comment by quentinocz** [comment]
Již bylo řečeno, že se na to někdo podívá spolu s dalším požadavkem cca před měsícem... Býval bych si to klidně zaplatil, ale platím zásilkovně a tudíž předpokládám, že zásilkovna platí tento modul a jeho vývoj. Je to jako čekání na godota, člověk tady dává konstruktivní feedback a místo reálného a skutečného data vyhotovení se dočká jen "podívá se na to někdy příští týden".. Chápu, že to někdy nelze dodržet přesně, ale aspoň reálný termín by byl dobrý.. Já, jakžto většina lidí tady staví pravděpodobně novou verzi svého eshopu a potřebuje nějak stanovit horizont dokončení a spuštění..
Děkuji tedy předem za sdělení přesnějšího termínu vyřešení těchto bugů a vylepšení
