### ISSUE TITLE
Translation issue

### ISSUE THREAD

**Issue by jbustamanterendon** [Zasilkovna/prestashop#23]
Hello,

There is no way to translate the text "- please choose -", attached screenshot to make it clearer.

![snap 2017-08-10 at 13 23 28](https://user-images.githubusercontent.com/12463284/29185630-6d9b04f8-7dcf-11e7-81b3-36bd88cae73f.png)

Best regards.

**Comment by matyx** [comment]
Thanks for report, we will fix this asap.

**Comment by quentinocz** [comment]
Hi @matyx , can you please give me an update on an estimated time to fix this?

**Comment by rivfaader** [comment]
Hi @quentinocz sorry for the delay, our developer should be able to get around to it some time next week

**Comment by quentinocz** [comment]
Any update on the process?
