### ISSUE TITLE
Download and Export buttons don't  work

### ISSUE THREAD

**Issue by levonhovs** [Zasilkovna/prestashop#24]
I have installed Zasilkovna module for prestashop 1.7 and have an issue when trying to download label or export order. Clicking on buttons there is no any action taken by module. Can you please help me?
![2017-08-22_21-24-15](https://user-images.githubusercontent.com/31256313/29583441-6bad6a72-8780-11e7-9445-8b019498a646.png)

**Comment by quentinocz** [comment]
Are you aware that the module now uses API? That means you do not have to download csv file and upload it on the Zasilkovna page. It does all automatically.. (check the package list in you zasilkovna account). Download labels should generate a link with a pdf file, this link should appear after pressing the button.
If nothing happens anyway, do you have entered an API pass correctly in the setting tab of the module?
If this does not help, please wait till somebody of the developers reply - I am just an user.

**Comment by levonhovs** [comment]
Thank you. Yes I have an API password entered and already have 10-12 test orders created but I cannot see them in Zasilkovna portal. Anyway thanks for your answer

**Comment by quentinocz** [comment]
Then, try turning on debug mode in PS. You can do so in the Performance settings. It might help to identify where to look for an error..

**Comment by levonhovs** [comment]
Done. But there is no any error. I think better to understand why it's not syncing with Zasilkovna portal.

**Comment by quentinocz** [comment]
Isn't it possible you used an API key instead of API password? It is quite easy to interchange as the previous version of the module used API key..

**Comment by levonhovs** [comment]
I have API password there. How I remember module will not allow you to add there API key. Do you know where I can check the API key in my PS files. It should be written somewhere, right?

**Comment by levonhovs** [comment]
Well, I understood. It's included in the password

**Comment by quentinocz** [comment]
Well, not sure with that as the API password starts with the API key and few more letters and numbers follow. Basically the API key is contained in the API password and there is probably no reason to store it somewhere "exclusively".. So I believe you will not find anything in the files..

**Comment by quentinocz** [comment]
What is your webhosting provider?

**Comment by levonhovs** [comment]
I have VPS hosted on 1and1 cloud.

**Comment by quentinocz** [comment]
I see, I do not suppose there would be any restrictions then causing the error in communication with zasilkovna. Can you provide me with backoffice access? I would try to have a look.

**Comment by levonhovs** [comment]
I have Zasilkovna account in test mode,I guess it also can be the reason of the issue

**Comment by matyx** [comment]
Hi there,
@levonhovs testing account should be functional as production, but the C. O. D. parcels. Can you try to send us orders without C. O. D. ?

**Comment by levonhovs** [comment]
Hi. I don't have the COD enabled in module.
![2017-08-22_22-35-01](https://user-images.githubusercontent.com/31256313/29586206-2c6041f0-878a-11e7-9a4b-1725e4070200.png)
![2017-08-22_22-33-19](https://user-images.githubusercontent.com/31256313/29586208-2c66016c-878a-11e7-8bdf-9d1214dfdd40.png)

**Comment by matyx** [comment]
Well, can you contact us at technicka.podpora@zasilkovna.cz? If you can provide access to your backoffice (testing env would be great), we can try to investigate where the problem is. We will update this issue as soon as we figure this out. 

Btw, thanks @quentinocz for helping :+1:, we appreciate it very much.

**Comment by levonhovs** [comment]
I already wrote you twice and last was today ))) Anyway, thank you guys. I will contact you by email once again.

**Comment by matyx** [comment]
Oh, I see. Sorry for delay, I will push this thing tomorrow :)
