### ISSUE TITLE
Zaokrúhľovanie

### ISSUE THREAD

**Issue by fifco** [Zasilkovna/prestashop#25]
Zdravím, 

v prípade dobierky v EUR sa suma zaokrúhli na celé eurá. 

Problém vidím na tomto riadku: 
https://github.com/Zasilkovna/prestashop/blob/3ba1be076a420f4ef2723628091270f1b4c226de/packetery/packetery.api.php#L239

Je takéto zaokrúhľovanie nastavené kvôli API? Je to, prosím, možné opraviť, tak aby sa suma v EUR zapisovala správne, aj s centami?

**Comment by quentinocz** [comment]
Teoreticky by mělo stačit v souboru přepsat na
$cod = $total;
Nicméně jsem to nezkoušel a nevím, zda nejsou někde další omezení, například, zda vzniklou hodnotu bude akceptovat server.. Můžete to však vyzkoušet. :)

**Comment by rivfaader** [comment]
Dobrý den, reálně se zakrouhlování liší měnu od měny v závislosti na nejnižší nominální hodnoty mince dané země (tzn např pro HUF musí být dobírka násobek 5)-

Bugreport jsme předali programátorovi a v blízké době bychom měli vydat opravenou verzi.
