### ISSUE TITLE
Mazání api.js

### ISSUE THREAD

**Issue by Turquess** [Zasilkovna/prestashop#26]
Netuším čím to, ale na testovacím webu se pravidelně maže soubor api.js a zůstává tam pouze api.js.error. Jakmile tam nahraji ten soubor znovu a nastavím mu práva na 644 celý den funguje a smaže se při první objednávce další den. Pokud je další objednávka až za 3 dny, tak se smaže až za ty 3 dny... PS 1.6.1.6

**Comment by rivfaader** [comment]
Takhle se modul chová v případě, že nedokáže opakovaně sám stáhnout aktuální verzi feedu. Tzn, že jste buď zadal chybný API klíč nebo selhává curl/fopen, v tomto případě je chyba na straně Vašeho serveru.

Kód který feed stahuje najdete v souboru packetery.php v metodě fetch().

Každopádně problém v tomto případě není na straně modulu.
