### ISSUE TITLE
Nelze přejít na výběr platby ve Firefoxu

### ISSUE THREAD

**Issue by zrazvymartin** [Zasilkovna/prestashop#27]
Při výběru dopravce ve Firefoxu se nelze dostat na další krok pomocí tlačítka Pokračovat. Tlačítko nereaguje. Při vypnutém modulu packetery to jde normálně.

Verze Prestashop 1.7.2.3

**Comment by zrazvymartin** [comment]
Nějaký pokrok s touto chybou, je to opravdu dost nepříjmné. Chcete to natočit na video?

**Comment by 100peck** [comment]
Máme tu samou chybu, dostali jsme odpověď 12.10, že chyba bude opravena v co nejbližší době. Zatím stále nic. Přicházíme kvůli tomu o prodeje.

**Comment by rivfaader** [comment]
Dobrý den, je nám líto, ale vývoj je outsourcován externímu zahraničnímu vývojaři, nemáme tedy bohužel přimou kontrolu nad rychlostí dodávání oprav.

Na opravě pracuje, dnes jsme dostali verzi k otestování ale oprava nebyla 100% funkční, bylo tedy vráceno k opravě.

Omlouváme se za komplikace.
