### ISSUE TITLE
Version 2.0.2 makes PS errors

### ISSUE THREAD

**Issue by quentinocz** [Zasilkovna/prestashop#28]
Hi, @rivfaader , the new version does not work.
1. the succesfully added to cart pop-up window doesnt work
3. the add to cart button works weirdly
2. I was unable to select city nor the pick up point in Safari and Chrome
See attachement
Works "fine" after downgrade to 2.0.1
<img width="1440" alt="snimek obrazovky 2017-10-25 v 11 57 28" src="https://user-images.githubusercontent.com/30895860/31992878-d7432dc6-b97b-11e7-8a2f-5e92fc083645.png">

**Comment by realmag1c** [comment]
@quentinocz 
Please check fixed version. Looks like everything works fine now. Please reload your javascript before test.
[packetery.v.2.0.2.zip](https://github.com/Zasilkovna/prestashop/files/1415657/packetery.v.2.0.2.zip)

**Comment by quentinocz** [comment]
@rivfaader 
Thanks, now it does not throw errors, BUT
It does select the country when there is only one option, but it does not show the list of cities then.. The customer is not able to select the city..
I use the OnePageCheckout module from @jbustamanterendon and it might be the issue of the module..
Can one of you guys have a look? @jbustamanterendon you have my FTP access and backoffice if needed..

And one more thing to improve - maybe, wouldnt it be possible to hide the country field at all when only one country is available as an option?:)
Tkanks and have a nice day!

**Comment by krasnycz** [comment]
@rivfaader I have the same issue as @quentinocz on 5 different stores using zasilkovna module with PS 1.7. Zasilkovna for PS 1.6. was compatible with @jbustamanterendon OPC module but PS 1.7 is not. Could you possibly make zasilkovna PS 1.7 module compatible with this OPC module too? Thank you in advance.

**Comment by realmag1c** [comment]
Can someone give me a copy of this OPC module for tests, then I can make fix for sure? to:(magrabota@gmail.com)
@quentinocz @krasnycz

**Comment by krasnycz** [comment]
@realmag1c Check email

**Comment by realmag1c** [comment]
Issue solved? @quentinocz @krasnycz

**Comment by quentinocz** [comment]
Everything works fine in my installation, did not spot any issue with this version so far.
