### ISSUE TITLE
Problem in order form in latest prestashop 1.7

### ISSUE THREAD

**Issue by gunzino** [Zasilkovna/prestashop#29]
Hello,

After I select packetery option in the order form, it won't show up the list of possible branchces. Therefore it is unable to use at all. It is happening for past months.

Thank you for fix!

**Comment by realmag1c** [comment]
Do you use 'One page checkout' modules? If yes - which one?

**Comment by gunzino** [comment]
Hello,

I managed to fix it myself. There was some conflicts that old version did not uninstalled properly
