### ISSUE TITLE
zobrazení dopravce v jedné řádce

### ISSUE THREAD

**Issue by cilecek** [Zasilkovna/prestashop#3]
dobrý den,
po instalaci modulu se mi dopravce zobrazuje ve dvou řádcích (první řádek název dopravce, druhý řádek výběr pobočky).

je nějaká možnost, jak dostat vše do jedné řádky (jako je u dopravce výše)?

díky,
milan

![zasilkovna-carr](https://cloud.githubusercontent.com/assets/11089873/15586780/7d257e02-2386-11e6-910c-9793b35fcdfa.png)

**Comment by Naxmars** [comment]
Dobrý den, 

problém je pravděpodobně způsoben použitím nestandardního košíku. Napište prosím email na technicka.podpora@zasilkovna.cz, sdělíme vám jaké jsou vaše možnosti.
