### ISSUE TITLE
Problem s výběrem pobočky 

### ISSUE THREAD

**Issue by dominikprucha** [Zasilkovna/prestashop#33]
Dobrý den. modul obsahuje tuto chybu. https://ibb.co/dN1UKm
Kdy prosím bude hotova oprava? mam poslední verzi modulu
Verze PrestaShopu: 1.7.2.2
Verze software serveru: Apache

Verze PHP: 5.6.32

Limit paměti: 256M

Max. doba provádění: 300

Max. velikost nahraného souboru: 120M

**Comment by rivfaader** [comment]
Dobrý den, můžete sem poslat odkaz na eshop k náhledu? Na první pohled to nevypadá jako chyba modulu, ale spíš jako změněná CSS na Vašem shopu.

**Comment by dominikprucha** [comment]
https://dreamwedding.cz. Web mi chybu neukazuje

**Comment by rivfaader** [comment]
Tak je to jak jsem se domníval, problém způsobuje JS plugin nice-select, který Vám upravuje funkcionalitu/vzhled select boxů. Nejedná se tedy o problém na straně pluginu.
