### ISSUE TITLE
Empty branch selection

### ISSUE THREAD

**Issue by JohnyProkie** [Zasilkovna/prestashop#35]
In checkout, if customer does not select branch, "Continue" button is disabled. Customer can still go directly to Payment method, therefore skipping branch selection.
Prestashop 1.7.2.2
how seen in module orders list - https://www.screencast.com/t/0C4AZg4nC
checkout - https://www.screencast.com/t/fbobnplFU

**Comment by packeta** [comment]
This bug has been fixed in the new module version 2.1.3
