### ISSUE TITLE
Broken Zásilkovna BO 

### ISSUE THREAD

**Issue by Konstantin-G** [Zasilkovna/prestashop#36]
Installed on Presta 1.7.2.4, Heslo API added, Branches are updated.
After some days module BO is broken.
printscreen: [https://drive.google.com/open?id=1f3Fwt9r3geSJhcAB-_I7CicKZ_P_e21J](https://drive.google.com/open?id=1f3Fwt9r3geSJhcAB-_I7CicKZ_P_e21J)

**Comment by realmag1c** [comment]
Hello @Konstantin-G,

There is no screenshots on drive - error 404.
Which error do you get? What do you mean about broken?

Have a nice day

**Comment by Konstantin-G** [comment]
Hello, just copy link to the google drive, i'll fix link later.

**Comment by Konstantin-G** [comment]
No feedback? OK!

**Comment by realmag1c** [comment]
Hello,
This is not a standard error. 
I can help you if you give me access to Back-office. Please contact me magrabota at mail.com

**Comment by packeta** [comment]
if this issue is still up-to-date, please let us know we will resolve it.
