### ISSUE TITLE
JS chyba

### ISSUE THREAD

**Issue by Soukee** [Zasilkovna/prestashop#37]
Dobrý den, 

již delší dobu řeším problém s Vaším modulem pro Prestashop 1.7
(https://github.com/Zasilkovna/prestashop). A sice, po nainstalování se
objeví JS chyba a tím pádem veškerá funkcionalita obchodu závislá na JS
odejde, což je zásadní problém. Na hraní máme obchod zde:
http://www.cm-tuning.cz

Po spuštění konzole v Google Chrome uvidíte chybu:

`Uncaught SyntaxError: Unexpected token u in JSON at position 0
    at JSON.parse (<anonymous>)
    at Object.readAjaxFields (front.js:101)
    at HTMLDocument.<anonymous> (front.js:33)
    at fire (core.js:690)
    at Object.fireWith [as resolveWith] (core.js:711)
    at Function.ready (core.js:745)
    at HTMLDocument.completed (core.js:748)`

Podotýkám, že tato chyba se objeví i na čisté instalaci. Netýká se však
Firefoxu. 

Chtěl bych se proto zeptat, víte o tomto problému? Budu vděčný za jakoukoli
informaci.

**Comment by Soukee** [comment]
For English speaking community:
Hello, 
I have a problem with your module for Prestashop 1.7 (https://github.com/Zasilkovna/prestashop). After installation there is a JS error which causes other problems with JS functionality. We have a demo shop here:
http://www.cm-tuning.cz

Google Chrome console shows following error:
`Uncaught SyntaxError: Unexpected token u in JSON at position 0 at JSON.parse (<anonymous>) at Object.readAjaxFields (front.js:101) at HTMLDocument.<anonymous> (front.js:33) at fire (core.js:690) at Object.fireWith [as resolveWith] (core.js:711) at Function.ready (core.js:745) at HTMLDocument.completed (core.js:748)`

This error occurs in clean install of Presta + your module as well. In Firefox is everything OK. 

I would like to ask you if you know this problem. Will appreciate every info about possible solution.

Thanks, P.

**Comment by realmag1c** [comment]
Hello,
You can fix at fork https://github.com/realmag1c/prestashop
Copy entire module or file /views/js/front.js

**Comment by realmag1c** [comment]
You can find fix at fork https://github.com/realmag1c/prestashop
Copy entire module or file /views/js/front.js

**Comment by realmag1c** [comment]
dont forget to reload Javascript (ctrl+F5)

**Comment by Soukee** [comment]
Thank you. When I replace front.js file, I get error:

> Uncaught SyntaxError: Unexpected token      front.js:7  <

Have a look at http://www.cm-tuning.cz/ pls.

**Comment by Soukee** [comment]
Looks that it works! I am going to test it! Thanks, P.
