### ISSUE TITLE
Multistore - zobrazení objednávek pouze pro výchozí obchod

### ISSUE THREAD

**Issue by Turquess** [Zasilkovna/prestashop#38]
Dobrý den,
používám multistore a při vytvoření objednávek v různých obchodech se při výběru konkrétního obchodu zobrazí pouze objednávky toho daného obchodu, což je skvělé, ale při zobrazení všech obchodů, se stále zobrazí pouze objednávky jednoho z obchodů, nikoli objednávky všech obchodů. Pro export je tak třeba vždycky projít zvlášť všechny obchody.

**Comment by realmag1c** [comment]
Hello,

I will check it and let you know about solution.

Have a nice day
Eugene

**Comment by Turquess** [comment]
Hello, some new info about solution? I have 4 store and now I need check and export all 4 stores separately.

**Comment by packeta** [comment]
Novou verzi modulu 2.1.3 jsme v multistore zatím netestovali, uděláme to co nejdříve.

**Comment by radar6** [comment]
Čekáme. Díky 😉

Dne pá 13. 12. 2019 8:04 uživatel packeta <notifications@github.com> napsal:
