### ISSUE TITLE
Mobilních zařízeních - neovladatelnost obchodu

### ISSUE THREAD

**Issue by PeNov** [Zasilkovna/prestashop#39]
Dobrý den,

v mobilních zařízeních dochází k chybám zobrazení, které mají za následek kompletní neovladatelnost obchodu.

Chyby:

**Android prohlížeč - různé verze př.: 4.1.2-s7710xxand2:
Chrome př.: 28.0.15000.94, 45.0.2454.84:**

- chybí tlačítko + a – u přidat množství
- tlačítko vložit do košíku
- pod množstvím dole se objeví tlačítko obnovit - link vede do košíku
- nelze přepínat karty popis, detaily produktu
- nefunkční hlavní menu, chybí logo, košík v hlavičce

**Android prohlížeč - různé verze př.: 4.4.4: a 4.0.20-57, 5.1647442**:

- chybí tlačítko + a – u přidat množství
- pod množstvím dole se objeví tlačítko obnovit - link vede do košíku
- nelze přepínat karty popis, detaily produktu
- nefunkční hlavní menu, chybí logo, košík v hlavičce

**Chrome 65.0.3325.109, 62.0.3302.84** - zobrazení je ok

Po zakázání modulu zasilkovna je vše korektně zobrazeno.

Zakázaní modulu zasilkovna skryje pole pro výběr poboček ale dopravce zasilkovna je stále možné vybrat a obj. dokončit bez pobočky.

Verze modulu: v2.0.3rc2
Verze PS: 1.7.2.4 a 1.7.3.0

Děkuji

**Comment by realmag1c** [comment]
Hello, 

Do you want to try [this](https://addons.prestashop.com/en/fast-mass-updates/30523-mass-price-quantity-products-categories-edit.html) Zasilkovna module for free?

Have a nice day

**Comment by PeNov** [comment]
Hello,

under link is module for Mass Price + Quantity + Products Categories Edit.

Something must be wrong.

Best regards

**Comment by realmag1c** [comment]
I meant https://addons.prestashop.com/en/collection-points-in-store-pick-up/28786-zasilkovna-pickup-points.html

**Comment by PeNov** [comment]
Yes, I can try this module on my test page.

What's different? At first glance it seems that the module is the same. Only different version of the module.
Is it a different module than is available for download in the administration zasilkovna.cz - as an official module?

**Comment by realmag1c** [comment]
Yes it is a little different.
Please give me your email.

**Comment by PeNov** [comment]
morfeus_2003@post.cz

**Comment by PeNov** [comment]
I uninstall and delete previous module. I install new version and configure. 
Result after a quick test:
errors still remain and plus one new error in administration.

List of carrier's delivery to the address is empty - is not possible configure.

list orders was loosed after uninstall - :-(

**Comment by PeNov** [comment]
Hello,

Some information about the new version?

In PHP log is a lot of this errors: 

[28-Jun-2018 13:23:44 Europe/Prague] PHP Notice:  Undefined variable: countBranches in /home/www/domain.cz/www/update.domain.cz/modules/packetery/packetery.api.php on line 419

Thank you

Best regards

**Comment by packeta** [comment]
V nové verzi modulu 2.1.3 jsme integrovali náš widget, který tyto problémy řeší lépe.   Pokud budete mít přece jen problémy se zobrazení widgetu na některém mobilním zařízením, napište nám prosím na widget@zasilkovna.cz ,  do emailu přidejte prosím název a typ mobilního zařízení, verzi Androidu nebo IOS.
