### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by romanb52** [Zasilkovna/prestashop#4]
Následující modul(y) nebylo možné zcela nainstalovat:

    packetery :
        Nelze nainstalovat přepsání: Class CarrierOverride576086007e787 does not exist

Presta: 1.6.1.5
module: latest (1.18, but 1.17 in config (!))

**Comment by rivfaader** [comment]
Dobrý den,

problém by mělo odstranit smazání souboru `./cache/class_index.php`.
