### ISSUE TITLE
Cannot choose contry / Nelze vybrat zemi

### ISSUE THREAD

**Issue by Prochj35** [Zasilkovna/prestashop#40]
Hi.
INFO: presta v. 1.7. , moduly: packatery-latest, packetery.v.2.0.0rc2 both with same issue

PROBLEM:
During the adding transporter, when i should pick countries, i saw only blank rows.
before select ->
<img width="565" alt="1 install selec country" src="https://user-images.githubusercontent.com/38661224/39230104-8ee817d4-4865-11e8-8d07-a02b60b51299.PNG">

after click into list, it select invisible row ->
<img width="563" alt="2 selected invisible" src="https://user-images.githubusercontent.com/38661224/39230105-8f062422-4865-11e8-9e78-a80941aa2bf9.PNG">
Installation set country to cz,sk with over 1500 branches. 

In order i have nothing to choose.
<img width="526" alt="3 otevreny listbox zeme" src="https://user-images.githubusercontent.com/38661224/39230107-8f2d2108-4865-11e8-913d-e505b55cdf6b.PNG">

Its show only empty lists with default values. (Země and nothing else)

CZ:
Ahoj, při přidávání dopravce při výběru země nelze nic vybrat. Obr. 1. Po kliknutí do listu to vybere prázdný řádek. Obr. 2. Přidá se mi dopravce a při výběru v eshopu když rozkliknu výběr země tak je tam práydný seznam pouze s defaultní hodnotou Země. Obr. 3.

**Comment by javor454** [comment]
bumping, this error occured on 2.0.3rc2

**Comment by Macin609** [comment]
PS:1.7.2.x  packetery:2.0.3rc2 

Stejný problém, avšak po vložení API hesla a aktualizaci poboček je to již v pořádku - seznam s výběrem zemí zobrazuje země.

**Comment by Prochj35** [comment]
Tak jsem to zkusil ještě jednou. Reinstal poslední verze. Vložení API hesla a aktualizace a bohužel v mém případě to vůbec nepomohlo. Vše je stejné jako v prvním příspěvku.

**Comment by packeta** [comment]
Stejný problém se řešil již v issue:  #46 .  V nové verzi modulu se během testování tento problém neobjevoval.
