### ISSUE TITLE
Filtr objednávek podle stavu

### ISSUE THREAD

**Issue by Turquess** [Zasilkovna/prestashop#41]
Dobrý den,
v exportu objednávek do zásilkovny se zobrazují všechny objednávky, včetně těch, které teprve čekají na platbu předem, ale není zde žádná možnost tyto objednávky odlišit od ostatních. Lze nějak exportovat pouze ty co jsou již zaplacené a nebo jsou na dobírku?

Děkuji Lukáš

**Comment by packeta** [comment]
Dobrý den, v nové verzi modulu filtrování přidáno zatím není.   Do budoucna filtry přidat plánujeme.
