### ISSUE TITLE
Modul pro Prestashop 1.6 nabízí jen některé pobočky

### ISSUE THREAD

**Issue by michalucen** [Zasilkovna/prestashop#42]
Čerstvě jsme nainstalovali modul pro Prestashop 1.6. (konkrétně máme 1.6.1.4). Vše funguje v pořádku, jen na výběr je podstatně méně poboček než má být (odhadem možná jen 100 pro Českou republiku). Pro Slovensko podobně velkáčást poboček chybí. Pobočky máme v administraci Zásilkovny standardně povolené všechny (zkoušeli jsme i manuálně povolit některou z těch co chybí ale bez úspěchu). V příloze screenshoty jako příklad - pobočka Boskovice pouze jedna, reálně tam jsou čtyři.
<img width="491" alt="screen shot 2018-04-30 at 17 32 00" src="https://user-images.githubusercontent.com/8898957/39435915-e1a43e9a-4c9c-11e8-8f88-92dbdadb06db.png">
<img width="1179" alt="screen shot 2018-04-30 at 17 35 15" src="https://user-images.githubusercontent.com/8898957/39435916-e1c80dac-4c9c-11e8-8b11-656d4f3f04c6.png">

**Comment by rivfaader** [comment]
Výdejní místa, která mají několik dní za sebou zavřeno (např prodloužený víkend jako je právě teď) se neexportují. Dnes/zítra by už v exportu být měly. Nejde o chybu modulu.
