### ISSUE TITLE
Vyber místa na mobilu nekdy nefunguje

### ISSUE THREAD

**Issue by quentinocz** [Zasilkovna/prestashop#43]
Relativně často se nám stává, ze zákazníci můžou potvrdit objednávku i bez výběru odběrného místa. Používáme OnePageCheckout od presteamshop.com, údajně nekdy ani nevyskoci tlačítko pro výběr místa, nemělo by to však ani dovolit potvrdit objednávku. Nepodařilo se nám problém blíže identifikovat, na našich zařízeních to funguje... Nevím, zda je chyba v modulu zasilkovny nebo OPC. Zákazníci hlásí dotčené objednavky z iPhone i Android.
Muzu poskytnout přístup k FTP.

Jde o quentino.cz

**Comment by quentinocz** [comment]
Hi there,
I am trying to remind you of ths issue.
Some of my customers have an issue displaying the branch selection on mobile devices (both Android and iOS). I was not able to specify the problem any further, on my iPhone and Android devices it works fine. It is really inconvinient to call customers after they order and ask where then want the package be sent...
I can grant you access to FTP, you can reach me at info(at)quentino.cz
I would really appreciate some of you, developers, to check on it and at least identify the issue.
Many thanks
DS

**Comment by packeta** [comment]
V nové verzi modulu 2.1.3 by již nemělo docházet k situacím,  že zákazník odešle objednávku bez výběru výdejního místa.   Modul zatím nebyl testován pro externí OnePageCheckout - toto budeme řešit v rámci #45
