### ISSUE TITLE
Výber krajiny pre doručenie na základe adresy doručenia

### ISSUE THREAD

**Issue by miroslavmurin** [Zasilkovna/prestashop#44]
PS 1.7.3.2 modul v.2.0.3rc2

Pri adrese doručenia na SK je možnosť vybrať všetky krajiny z nastavenia modulu( mám nastavené SK,CZ). Tzn. adresa doručenia SK a v module som vybral výdajné miesto v CZ a naopak.

**Comment by PeNov** [comment]
Toto jsem také řešil. Lze obejít přes zóny, ale není to ideální. Také budu rád za opravu.

**Comment by packeta** [comment]
Počínaje novou verzí modulu 2.1.3 funguje nastavení zemí pro widget následujícím způsobem:  
- pokud vyberete u jedné přepravní metody více států (např. CZ, SK) přepravní metoda se v košíku nabídne v případě, že si kupující vybere dodací adresu v CZ nebo SK.   Vždy se ale ve widgetu zobrazí výdejní místa země z dodací adresy.
