### ISSUE TITLE
Funkčnost modulu s Onepagecheckout moduly

### ISSUE THREAD

**Issue by Nikstep** [Zasilkovna/prestashop#45]
Zdravím, 

dokončujeme web na prestě 1.7 a používáme jednokrokovou objednávku, ale po instalaci modulu nemáme možnost vybrat pobočku zásilkovny. 

Řešili jste už podobný problém? 

Díky
N.S.

**Comment by mardon** [comment]
Mám stejný problém s modulem Supercheckout od Knowband na prestashopu 1.6. Nezobrazí se výběr pobočky

**Comment by Nikstep** [comment]
bump

**Comment by mardon** [comment]
zatím žádné řešení problému, diky za odezvu

**Comment by Nikstep** [comment]
Zdravím,

věnovali jsme tomu 10 hodin programátora a ani Zásilkovna ani Twisto jsme
nenaimplementovali, tak jsme změnili OPC modul na "One Page Checkout
PrestaShop" od PresTeamShop

S pozdravem
Stěpanov

po 8. 10. 2018 v 13:08 odesílatel mardon <notifications@github.com> napsal:

**Comment by quentinocz** [comment]
Ja mam supercheckout a sami knowband mi opravili kompatibilitu a veskere problemy, ktere jsem s modulem mel.
OPC od presteamshop jsem mel, ale v nem mi (ne chybou OPC) u nekterych objednavek se neulozilo ani nezobrazila volba pobocky a musel jsem pak lidem volat... v supercheckout toto nejak vyresili a ted uz absolutne bez problemu:)
Staci jim napsat a opravi vse co se kompatibility s jinymi moduly tyce:)

**Comment by quentinocz** [comment]
Ano.

**Comment by packeta** [comment]
Dobrý den,   vydali jsme novou verzi modulu 2.1.3.  Tuto verzi  jste zatím testovali na košíky, které jsou ve výchozí instalaci PrestaShopu 1.7 (standartní pětikrokový a jednokrokový).  Pro další (placené) Onepagecheckouty jsme modul zatím neupravovali.  V dalších verzích plánujeme upravit modul pro nejvíce využívané košíky.   Budeme rádi, když sem přidáte návrhy, které moduly jsou podle vás nejvíce používané.

**Comment by romanseki** [comment]
zdravim, nejaky posun s opc modulmi? skusal som knowband aj onepagecheckout ps a ani v jednom zasielkovna nefunguje

**Comment by ShaiMagal** [comment]
Zdravim,

muzete vyuzit muj modul, ktery je plne aktualni a plne kompatibilini se vsemi znamymi OPC jako je napriklad onepagecheckout apod, vice zde:

https://psmoduly.cz/zasilkovna-vyber-odberneho-mista-primo-v-objednavce-novy-widget-2020-api-prenos-zasilek-269/prestashop-1-6-1-5.htm

**Comment by packeta** [comment]
> zdravim, nejaky posun s opc moduly? zkoušel jsem knowband i onepagecheckout ps a ani v jednom Zásilkovna nefunguje

Dobrý den,   napište nám prosím na technicka.podpora@zasilkovna.cz  jakou podporu OPC pro Váš eshop potřebujete.
