### ISSUE TITLE
Nekompabilita s One Page Checkout PrestaShop

### ISSUE THREAD

**Issue by Alkotronikk** [Zasilkovna/prestashop#5]
Při použití One Page Checkout modulu nefunguje u zásilkovny výběr odběrného místa z vysouvacího seznamu - při výběru nelze pokračovat v nákupu jako by nebylo vybráno nic. Toto však platí pouze při nákupu na dobírku, klasická platba předem tímto problémem netrpí.

**Comment by toretak** [comment]
K problemu nedochazi, pokud neni na vyber zadny jiny zpusob dopravy.

**Comment by rivfaader** [comment]
Problém by v nové verzi pro PS 1.7 neměl existovat
