### ISSUE TITLE
Update of branches is necessary to made manually

### ISSUE THREAD

**Issue by marektryner** [Zasilkovna/prestashop#58]
Prestashop version 1.7.6.2
Module version 2.1.3

There is a necessary to start manualy the update of branches. 
The update won't start automatically and there is not a option to add the update of branches to cron task list.

**Comment by quentinocz** [comment]
Tento modul není už dávno podporován, je zastaralý a žádné úpravy tedy nelze čekat. Doporučuji přejít na placený modul viz. odkaz níže, sám jej používám a můžu jen doporučit.

https://psmoduly.cz/zasilkovna-vyber-odberneho-mista-primo-v-objednavce-novy-widget-2019-api-prenos-zasilek-269/prestashop-1-6-1-5.htm?search_query=Zasilkovna&results=31

**Comment by marektryner** [comment]
> Tento modul není už dávno podporován, je zastaralý a žádné úpravy tedy nelze čekat. Doporučuji přejít na placený modul viz. odkaz níže, sám jej používám a můžu jen doporučit.
> 
> https://psmoduly.cz/zasilkovna-vyber-odberneho-mista-primo-v-objednavce-novy-widget-2019-api-prenos-zasilek-269/prestashop-1-6-1-5.htm?search_query=Zasilkovna&results=31

Modul byl aktulizován na verzi 2.1.3 před 2 měsíci a podporovaný je přímo ze zásilkovny se kterou jsem mluvil osobně telefonicky. Je spíše málo času na jeho údržbu a tak jsou změny drobné. Každopádně díky za odkaz, pokud by se modul dále nevyvíjel, přejdu ke konkurenci.

**Comment by quentinocz** [comment]
Ok, omlouvám se, nevšimnul jsem si, že se to tady nějak pohnulo.. před pár měsící zásilkovna oznámila přechod na nový způsob zobrazování výběru poboček a tomu předcházel nejméně dobrý půlrok, možná víc, co se tady nedělo nic, modul ve většině případů nefungoval správně a na podpoře byli schopni říct maximálně, že plánují něco v budoucnu... tak či tak vzhledem k tomu, jak podpora po nějaké době zmizela poprvé bych raději volil tu placenou verzi, kde je jistota rychlé podpory a opravy vždy... :)

**Comment by packeta** [comment]
Dobrý den, 

s udržováním a vývojem modulu pro PrestaShop počítáme i do budoucna.  Všechny naše moduly vydáváme jako open source.   Aktuální verze modulu plně integruje náš widget.   V další verzi bychom chtěli přidat podporu multistore a upravit modul pro nejpoužívanější one page košíky třetích stran.
