### ISSUE TITLE
Allow multiple countries for carriers.

### ISSUE THREAD

**Issue by josle711** [Zasilkovna/prestashop#59]
Allow multiple countries for carriers.
(e.g.: Czech Republic, Belgium, Bulgaria, Croatia, Denmark, Estonia, Finland, France, Ireland, 
Italy, Lithuania, Latvia, Luxembourg, Hungary, Netherlands, Germany, Poland, Portugal, 
Austria, Romania, Russia, Slovakia, Slovenia, United Kingdom, United States of America, Ukraine, Greece, Spain, Switzerland)

**Comment by packeta** [comment]
The module supports delivery to an address by Packeta via external carriers. You can assign an external carrier of Packeta to each carrier and choose Cash on Delivery in the Cash on Delivery column.
