### ISSUE TITLE
Unable to select branch on mobile chrome or safari.

### ISSUE THREAD

**Issue by askdesigners** [Zasilkovna/prestashop#60]
When using the pop-up widget for selection of branches on mobile, the button at the bottom is not visible. Is there something I need to do to make the iframe properly resize the contents?
![IMG-6721](https://user-images.githubusercontent.com/2891457/74910946-e7baf300-53bb-11ea-878e-2d2303c2d68d.png)
![IMG-6720](https://user-images.githubusercontent.com/2891457/74910951-ebe71080-53bb-11ea-89f7-08b1447acd9d.png)

**Comment by askdesigners** [comment]
nothing?

**Comment by packeta** [comment]
The module uses a widget to select dispensing points - http://widget.packeta.com/
If this widget is displayed incorrectly on your mobile phone, please contact our technical support technicka.podpora@zasilkovna.cz
