### ISSUE TITLE
Chybí tlačítko k uložení API

### ISSUE THREAD

**Issue by radar6** [Zasilkovna/prestashop#61]
Aktualizoval jsem na nejnovější verzi a bohužel mi nastavení API zmizelo. Zjistil jsem, že tam chybí tlačítko k uložení nastavení. Co s tím? Setkal se s tím někdo?
Mám Prestashop 1.7.6.1., multistore
Mimochodem kompletní odinstalování a nové nainstalování nepomohlo.

**Comment by radar6** [comment]
Stejná situace na 1.7.6.3 bez multistore

**Comment by zemekoule** [comment]
Dobrý den,  tlačítko zde není protože se data po vyplnění ukládají automaticky  Pokud jste aktualizoval na nejnovější verzi ,  nedošlo pravděpodobně ke změně struktury databáze.  Je proto potřeba databázi aktualizovat ručně a spustit SQL dotaz, který je uveden zde:  #55

**Comment by radar6** [comment]
Dobrý den, ale tím dotazem jsem přidal to samé, co jsem před tím vymazal, protože jsem tu starou instalaci vč. tu přeinstalovanou na tu novou, úplně smazal a nainstaloval jsem čerstvou instalaci. Takže to nefunguje. Viz stejně tak jak popisuji výše, tak to nefunguje ani na nově nainstalovaném Prestashopu.

**Comment by zemekoule** [comment]
> Dobrý den, ale tím dotazem jsem přidal to samé, co jsem před tím vymazal, protože jsem tu starou instalaci vč. tu přeinstalovanou na tu novou, úplně smazal a nainstaloval jsem čerstvou instalaci. Takže to nefunguje. Viz stejně tak jak popisuji výše, tak to nefunguje ani na nově nainstalovaném Prestashopu.

Jestliže vám to opravdu nefunguje, napište nám na technicka.podpora@zasilkovna.cz ,  pokud nám dáte přístup do eshopu,  podíváme se , kde je problém.
