### ISSUE TITLE
Nahodne nevygenerovanie zasielok z Presta do zasilkovny

### ISSUE THREAD

**Issue by profi-hair** [Zasilkovna/prestashop#63]
Zdravim,

urobil som upgrade z 1.6 na 1.7 a nsledne na najnovsiu veriu zasilkovna.cz
Prvy problem bol non-update paremetres tabulky.
To som vyriesil.
Ale teraz si vsimam, ze sa nahodne nedari exportovat z presta zasielky do zasilkovna.cz.
Ziadna akcia, ziadny error
nemate ejaky navod?

dik

Rudo

**Comment by quentinocz** [comment]
Pořiďte si modul od psmoduly.cz, ten od zasilkovny stoji za...ehm..

**Comment by packeta** [comment]
Dobrý den,   pokud problém trvá napište nám prosím na technicka.podpor@zasilkovna.cz více podrobností- co konkrétně mysoíte tím, že se nedaří exportovat ?  Zásilky k exportu vůbec nevidíte, nebo export skončí nějakou chybou ? Určitě to budeme řešit.

**Comment by profi-hair** [comment]
Už som si kúpil komerčný modulDik
    	
    	

    	Rudo Schimik +420 737 268 656
    
  




On Fri, Oct 16, 2020 at 5:44 PM +0200, "packeta" <notifications@github.com> wrote:
















Dobrý den,   pokud problém trvá napište nám prosím na technicka.podpor@zasilkovna.cz více podrobností- co konkrétně mysoíte tím, že se nedaří exportovat ?  Zásilky k exportu vůbec nevidíte, nebo export skončí nějakou chybou ? Určitě to budeme řešit.
