### ISSUE TITLE
Nelze podat zásilky

### ISSUE THREAD

**Issue by Squatter2** [Zasilkovna/prestashop#64]
Dobrý den,
prosím o pomoc: zprovozňuji modul a nelze podávat zásilky. V konzoli se při stisknutí tlačítka zobrazí následující chyba:
![image](https://user-images.githubusercontent.com/35115448/98991725-88de7080-252c-11eb-8444-aead9a094d99.png)

Díky za pomoc!

**Comment by zemekoule** [comment]
Dobrý den,  zkuste si prosím vypnout údržbu obchodu (pokud jej máte zapnutý). Pokud to nepomůže, napište nám prosím na technicka.podpora@zasilkovna.cz . Budeme potřebovat přístup do vašeho eshopu, abychom zkontrolovali všechna nastavení.

**Comment by fstepanovsky** [comment]
@Squatter2 řešil jsme stejný problém, nakonec problém vyřešilo doinstalování php modulu (**php-soap**), máte ho nainstalovaný?

@zemekoule bylo by možné ho zmínit v README.md? Koukal jsem, že už byla opravena šablona, která toto kontroluje  https://github.com/Zasilkovna/prestashop/commit/1a4d0b6721a112647630d9ea273293fa5a1e2336#.

Bylo by dobré to vydat i jako release, díky!

**Comment by zemekoule** [comment]
@Squatter2 pokud jste váš problém ještě nevyřešil, napište nám  na technicka.podpora@zasilkovna.cz.  Budeme potřebovat přístup do vašeho eshopu a podíváme se, kde je problém.

@fstepanovsky díky za upozornění , do README.md tuto informaci přidáme, stejně tak i vydáme nový release
