### ISSUE TITLE
Prestashop 1.7.7.3 stuck/freeze during upgrade

### ISSUE THREAD

**Issue by Radek100** [Zasilkovna/prestashop#88]
During upgrade using 1-click prestashop modul from version 1.7.7.3 (clean installation) to 1.7.7.4 it stuck/freeze before upgrading modules. Get this message where it stuck: FrontController.php line 359 - Trying to get property 'logged' of non-object  Check print screen [https://ibb.co/rGbqRQW](url)

Not sure if MySQL version 8 isn't the problem. Is it compatible with version 8?

Thank you
Best regards
Radek

**Comment by jan-potuznik-z** [comment]
Hi Radek, we tested the module with MySQL 8 and everything went fine. What makes you think that problem is caused by this module?

**Comment by Radek100** [comment]
Hi,

as I attached image with issue. This already happened with my previous version 1.7.7.3 with more modules installed. I coudn't finish the upgrade because it always stuck. So I decided to install clean installation and try modules separately and I found this happened only if packata module is installed. So I tried upgrade clean Prestashop without any module and upgrade was ok. Then I tried upgrade clean installation with packeta and it stuck.

If I uninstalled packeta module it gave me the same problem. Until I uninstall the module and check delete module files then the upgrade was ok. 

I tried to download all ecommerce to xampp and there was upgrade ok. But there was different version of MySQL. I can't find any different things. My hosting is on OneBit.

If there is possibility to share acccess I can provide you testing site with domain online. But I don't know how. This is my first post on Github. 

I turned on debug mode and checked upgrade log. But no any specific information only : FrontController.php line 359 - Trying to get property 'logged' of non-object. Which also appear on xampp but it didn't stuck on this. 

Best regards
Radek

**Comment by jan-potuznik-z** [comment]
I suggest following steps:
Please provide module version and PHP version (copy of php_info() result ideally)
(Maybe it differs from your XAMPP's PHP version?)
Also please check error.log (can be turned on at OneBit).
Have you checked PrestaShop's error log?

**Comment by Radek100** [comment]
packeta v2.1.5

PHP version Onebit: 7.3.28
PHP version Xampp:  7.3.28
Verze MySQL Onebit: 8.0.23
Verze MySQL Xampp: 5.1.0

Here is the php_info() from OneBit [https://ibb.co/fvGpgwq](url)
This is php.ini from Xampp [https://drive.google.com/file/d/1Tkh_eke6Z8gPY1K14Yg1Y9KnGME_pZ2y/view?usp=sharing](url)

I have no idea if this can make some influence but when I moved to Xampp with MySQL 5.1.0 I had to change this:

utf8mb4_0900_ai_ci to utf8_unicode_ci
utf8mb4 to utf8
utf8_unicode_520_ci to utf8_unicode_ci

I had turned on error.log on Onebit - no error message.
I checked only autoupgrade/tmp/log.txt where was only infromations same as I see in upgrade window

I didn't check prestashop error log.

# I have suspicion, that the reason is already fixed in upcoming release.
When it should be released?

**Comment by jan-potuznik-z** [comment]
Thanks to your report it will be very soon, I'll reach back to you.

**Comment by jan-potuznik-z** [comment]
We're finishing new version 2.1.6 which should be released this week.

**Comment by Radek100** [comment]
Hello,

perfect thank you for let me know. Should I try upgrade from 1.7.7.3 to 1.7.7.4 or it is 100% fixed?

Best regards
Radek

**Comment by jan-potuznik-z** [comment]
Hello, described problem causing "Trying to get property 'logged' of non-object." error is fixed.

**Comment by jan-potuznik-z** [comment]
Hello, unfortunately there are a few more issues we need to address. We want to release a new version by the end of May and we will write here as well.

**Comment by Radek100** [comment]
Ok, thank you for info

**Comment by jan-potuznik-z** [comment]
Hello, new version is available for download here: https://github.com/Zasilkovna/prestashop/releases/tag/v2.1.6
Can you please confirm that it fixes your issue?
