### ISSUE TITLE
Trying to get property id and id_carrier

### ISSUE THREAD

**Issue by PeNov** [Zasilkovna/prestashop#98]
Hello,
new module ver. 2.1.5 generate many PHP notice in log file:

`[31-May-2021 13:03:46 Europe/Prague] PHP Notice:  Trying to get property 'id' of non-object in /home/www/DOMAIN.cz/www/DOMAIN.cz/modules/packetery/packetery.class.php on line 322
[31-May-2021 13:03:46 Europe/Prague] PHP Notice:  Trying to get property 'id_carrier' of non-object in /home/www/DOMAIN.cz/www/DOMAIN.cz/modules/packetery/packetery.class.php on line 323`

Tested on PS 1.7.7.4
PHP: 7.3.27-1~deb10u1
MySQL: 10.1.48-MariaDB-0+deb9u2

Thank you
Best regards
PN

**Comment by ZeeCap** [comment]
Hello,

today we released a new version 2.1.6 which fixes this issue - https://github.com/Zasilkovna/prestashop/releases/tag/v2.1.6

Please, install this new version. If the problem still persists, let us know. 👍

**Comment by PeNov** [comment]
Hello,

new version 2.1.6 generate a similar notice:
`[10-Jun-2021 13:20:29 Europe/Prague] PHP Notice:  Trying to get property 'id_carrier' of non-object in /home/www/domain.cz/www/domain.cz/modules/packetery/libs/Order/OrderSaver.php on line 35`

![image](https://user-images.githubusercontent.com/38213520/121542556-85e72800-ca08-11eb-9c0d-b9a22bb5407b.png)


Thank you
Best regards
PN

**Comment by MatyasKoval** [comment]
Hello @PeNov, 
I am currently going through old issues opened in our modules. I believe this behaviour is no longer happening as we are currently able to test our modules a lot more before releasing. 

Nevertheless, if you are still encountering this issue on the newer versions of our module, please do let us know.

Best regards,
Matyáš Kovaľ - Packeta IT support
